# Generated by Django 4.2 on 2025-05-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderDetail',
        ),
    ]
