# Generated by Django 4.2 on 2025-05-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_total_orders_product_total_sales_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
